version: '3.9'

services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3011:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabasedb
      - MB_DB_PORT=5432
      - MB_DB_USER=metabaseuser
      - MB_DB_PASS=atlantic-washhouse-bulk
      - MB_DB_HOST=db
    restart: unless-stopped
    
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.11
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3012:3000"
    volumes:
      - /datadrive/data/uptim-kuma:/app/data